// Auto-generated by frontend/build_report.py. Rebuild instead of editing.
window.GEOSYNTH_REPORT = {
  "generated": "2026-04-02T11:55:24",
  "kpi": {
    "task_families": 2,
    "datasets": 3,
    "tracked_samples": 2941,
    "checkpoints": 2,
    "preview_panels": 5,
    "artifacts": 11
  },
  "datasets": [
    {
      "name": "roads",
      "train": 72,
      "val": 14,
      "status": "READY"
    },
    {
      "name": "water_land",
      "train": 2273,
      "val": 568,
      "status": "READY"
    },
    {
      "name": "changes",
      "train": 12,
      "val": 2,
      "status": "READY"
    }
  ],
  "histories": {
    "roads": {
      "train_loss": [
        0.5172121334407065
      ],
      "val_loss": [
        0.6867423057556152
      ],
      "train_dice": [
        0.0418996548540896
      ],
      "val_dice": [
        0.001142204454596648
      ]
    },
    "changes": {
      "train_loss": [
        0.5045738418896993
      ],
      "val_loss": [
        0.9090759754180908
      ],
      "train_dice": [
        0.05197805371064186
      ],
      "val_dice": [
        0.03565517241378081
      ]
    }
  },
  "metrics": {
    "roads": {
      "epochs": 1,
      "val_loss": 0.6867423057556152,
      "val_iou": 0.0005714285714282086,
      "val_dice": 0.001142204454596648,
      "val_precision": 0.10227272726110538,
      "val_recall": 0.0005743092336158673
    },
    "changes": {
      "epochs": 1,
      "val_loss": 0.9090759754180908,
      "val_iou": 0.01815117789558047,
      "val_dice": 0.03565517241378081,
      "val_precision": 0.018175426261199445,
      "val_recall": 0.9315315315147472
    }
  },
  "predictions": {
    "roads": [
      "../outputs/predictions/roads/roads_preview_0.png",
      "../outputs/predictions/roads/roads_preview_1.png",
      "../outputs/predictions/roads/roads_preview_2.png"
    ],
    "changes": [
      "../outputs/predictions/changes/changes_preview_0.png",
      "../outputs/predictions/changes/changes_preview_1.png"
    ]
  },
  "registry": [
    {
      "key": "Platform",
      "val": "GeoSynth",
      "sub": "remote sensing dashboard"
    },
    {
      "key": "Task Modes",
      "val": "Segmentation + Change",
      "sub": "shared backend"
    },
    {
      "key": "Road Checkpoint",
      "val": "roads_best.pth",
      "sub": "current best file"
    },
    {
      "key": "Change Checkpoint",
      "val": "changes_change_best.pth",
      "sub": "current best file"
    },
    {
      "key": "Prediction Panels",
      "val": "5",
      "sub": "saved qualitative outputs"
    },
    {
      "key": "Histories",
      "val": "2",
      "sub": "roads and changes"
    },
    {
      "key": "Generated",
      "val": "2026-04-02 11:55:24",
      "sub": "build_report.py"
    },
    {
      "key": "Serving",
      "val": "frontend/",
      "sub": "static local page"
    }
  ]
};
